### ISSUE TITLE
Build real_syscall in a separate static library

### ISSUE THREAD

**Issue by daniel-grumberg** [srg-imperial/SaBRe#41]
Currently, a plugin needs to link against the all the architecture dependent code to get the `real_syscall`  symbol, pulling in the entire loader, which is not ideal. Furthermore, this means the the loader needs to be compiled with `-fPIC`when it really should only be `-fPIE`.

**Comment by daniel-grumberg** [comment]
I am happy to deal with it if people are happy with the suggestion.

**Comment by parras** [comment]
So you're suggesting to take `real_syscall` out of the arch libs and have the plugins link directly against it, are you?

**Comment by parras** [comment]
Oh I missed the title! Yes, a separate library is fine.
